
# For SNK G1 LED CONTROL
obj-y			+= g1_led.o

# For SNK G1 USB HUB POWER CONTROL
obj-y			+= g1_usb_hub_power.o

#
# For encryption
#
obj-y			+= umido_core.o
umido_core-objs	:= sw2001.o sw2001_aes.o

