#
# Makefile for PMU
#

obj-y			+= atc260x_core.o
atc260x_core-objs	:= atc260x_dev.o atc260x_spi.o  atc260x_mfp.o atc260x_irq.o atc260x_i2c.o

obj-y			+= atc260x_dcdc.o
obj-y			+= atc260x_ldo.o
obj-y			+= atc260x_switch_ldo.o
obj-y			+= atc260x_pm.o
obj-y			+= atc260x_onoff.o
#obj-y			+= atc260x_rtc.o
obj-y			+= atc260x_gpio.o
# obj-y			+= atc260x_hwmon.o
